name: Cypress Tests

on:
  push:
    branches:
      - ci
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Start Cypress HTML Report Server
        run: node ./startReportServer.js &
        continue-on-error: true

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/reports/html/index.html
