name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Setup Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

    
      - name: Generate Cypress HTML Report
        run: |
          node ./startReportServer.js &  # Executa o servidor em segundo plano
          sleep 5  # Aguarda o servidor iniciar

    
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      
      - name: Rename Report.html to index.html
        run: |
          mv TestReport/Report.html TestReport/index.html

  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: TestReport 
