name: Cypress Tests

on:
  push:
    branches:
      - ci
  pull_request:
  
permissions:
  contents: write
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: '20'  
          
      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Generate Cypress HTML Report
        run: |
          node ./startReportServer.js &  
          sleep 5  

      - name: Rename Report.html to index.html
        run: |
          mv TestReport/Report.html TestReport/index.html

      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4  
        with:
          name: cypress-report
          path: TestReport/index.html  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestReport
